# Generated by Django 4.2.7 on 2026-03-09 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dur', models.FloatField()),
                ('spkts', models.FloatField()),
                ('dpkts', models.FloatField()),
                ('sbytes', models.FloatField()),
                ('dbytes', models.FloatField()),
                ('rate', models.FloatField()),
                ('sttl', models.FloatField()),
                ('dttl', models.FloatField()),
                ('sload', models.FloatField()),
                ('dload', models.FloatField()),
                ('prediction', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
